### ISSUE TITLE
Unplayable with Xbox one controller

### ISSUE THREAD

**Issue by Dmi3ii** [ekunuke/vagante_issues#80]
Good day everyone.
After multiplayer update i have issue (dropped frames) with my Xbox one controller on win 10.
The legs do not appear on the start screen. It starts happens on hero select and so on.
The game became almost completely unplayable.
But it seems to be ok, when my expensive controller is off!

In "device manager" - "network adapters" i see "Xbox Wireless Adapter for Windows". Maybe game try to work with that as an network adapter?

Help! I miss my game T__T

**Comment by ekunuke** [comment]
I added specific support for xbox one wireless adapters, please let me know if your problem persists after the next game patch.

**Comment by Dmi3ii** [comment]
39a

Still have that issue. It seems getting worse. Now it drops frames at the start screen.
And i can't rebound alternative move at my LPAD...
![image](https://cloud.githubusercontent.com/assets/12540464/14151545/1090d0ee-f6b7-11e5-9d29-bb7176e699d5.png)

[log.zip](https://github.com/ekunuke/vagante_issues/files/196073/log.zip)

**Comment by ekunuke** [comment]
So disregarding the issue of alternate move not binding (for now), your only issue is dropped frames?

Are you playing the game with vertical sync enabled in the game settings?

**Comment by Dmi3ii** [comment]
vsync does not mater. I was playing with my nvidia driver as well. Reinstall Vagante. I have tried to clean system out of anything.
When that wireless Xbox one is on, game drops frames. And when it off, and i use keyboard game works fine. As well as i connect my old f****g controller (logitech k790i)
That makes me think, that you have problem only with M$ controllers.

(I will try it on my friends machine, as soon as i can)

But you should buy one for testing purposes)). Or i am a fool, or game is not ready for win10

**Comment by ekunuke** [comment]
After doing some research, I think this might be the same problem as what people describe here: https://www.reddit.com/r/pcgamingtechsupport/comments/3rs0mv/xbox_one_controller_causes_fps_stuttering_and_lag/

It looks like users are reporting the lag goes away after manually updating their gamepad software, following the steps here: http://support.xbox.com/en-US/xbox-one/accessories/update-controller-for-stereo-headset-adapter

Any chance you could give this a try?

**Comment by Dmi3ii** [comment]
I have just updated the device. Thank you for info =)
![image](https://cloud.githubusercontent.com/assets/12540464/14180966/d28d7786-f76d-11e5-83af-602be869824a.png)

But i still have that issue. 39c

ekun, must admit, i was playing on this computer with this settings in your game just fine before multiplayer come out. You still think trouble on client side? >:-)

And still can't rebound alternative movement. Sending you screenshot.

![image](https://cloud.githubusercontent.com/assets/12540464/14180925/ae3c65d6-f76d-11e5-92a7-4a489502bb06.png)

**Comment by Dmi3ii** [comment]
(It was experiment sorry). Just tried to install and play v34c. And you guess what? It's playble!
And key binding working and everything alright.

![image](https://cloud.githubusercontent.com/assets/12540464/14181912/c12a495c-f771-11e5-95ac-2468a33c73d2.png)

**Comment by ekunuke** [comment]
> i was playing on this computer with this settings in your game just fine before multiplayer come out. You still think trouble on client side? >:-)

I was suspecting a windows update of some kind to have changed how it works, but now I believe you :P 

Thanks for the details screenshots, I'm going to do my best to fix this right now.

**Comment by ekunuke** [comment]
I just pushed Patch 39d. I think this may fix your performance issues, but the alternate movement issue is something I still need to look into.

**Comment by Snakewilliams** [comment]
Hey, I've actually had the same issue. I just tried the controller update with 39d and lag/stutter still occurs with wireless xbox one controller.

**Comment by Dmi3ii** [comment]
> I think this may fix your performance issues

I confirm. Problem still exsist. 39d

**Comment by ekunuke** [comment]
:( I've tried playing with my own xbox one controller and I can reproduce the issue as well.

I've done a little bit of research and it looks like some other games suffer the same issue with xbox one controllers: https://docs.google.com/document/d/1S9TYncPj8Gttq1dIaQgXh4ekuQhCFwU_CXGQ6Y1Xh9E/edit?usp=sharing

**Comment by Dmi3ii** [comment]
Why can't you compare v34c with current code? And find out what was right in older versions?
I do not compare other games. I compare vagante with itself!

**Comment by Snakewilliams** [comment]
Its super weird though, I have no problems with other games, and this only started with the last couple patches

**Comment by Snakewilliams** [comment]
On a strange note, I've been uninstalling and reinstalling the device, updating controllers, anything I could think of, but I may have figured something out, I have a Logitec keyboard and a g13 mini keyboard thing that runs a program  to configure the macros. I shut this off and tried running the game and noticed no lag. Not exactly sure why this would be as I'm not terribly driver savvy, I can only imagine that there must be a driver conflict somewhere. I'll play a few more rounds just to make sure its gone and report back.

**Comment by Snakewilliams** [comment]
The very next round I started getting the lag/stutter again. I might have to go back to my wired controller, as this is one of my favorite games and the wireless thing makes it unbearable. I'll let you know if I ever find something that works though.

**Comment by Dmi3ii** [comment]
39e. Progress!
It seems, like issue almost solved! What have you done? =)
I still have a little stutter while playng with conroller, but it'is berable (playable).
And still with keyboard only i have no issues at all.

**Comment by ekunuke** [comment]
I'm in the middle of adding official XInput support to Vagante, which hopefully fixes these issues once and for all.

**Comment by Dmi3ii** [comment]
You did it!
Well done =)
